#!/usr/bin/env python3
"""
Build script для сборки index.html из секций и admin.bundle.js из модулей.

Использование:
    python3 build.py              # Собрать index.html и admin.bundle.js
    python3 build.py --watch      # Собрать и следить за изменениями
    python3 build.py --admin-only # Собрать только admin.bundle.js

Порядок секций определён в SECTIONS.
Порядок модулей admin определён в ADMIN_MODULES.
"""

import os
import sys
import time
from pathlib import Path

# Порядок секций для сборки index.html
SECTIONS = [
    'head.html',
    'navigation.html',
    'marquee.html',
    'hero.html',
    'services.html',
    'podology.html',
    'masters.html',
    'location.html',
    'social.html',
    'blog.html',
    'faq.html',
    'booking.html',
    'blog-modal.html',
    'footer.html',
    'scripts.html',
]

# Порядок модулей admin для сборки admin.bundle.js
# ВАЖНО: порядок имеет значение - зависимости должны идти раньше зависящих модулей
ADMIN_MODULES = [
    # Core modules (без зависимостей)
    'state.js',
    'toast.js',
    'api.js',
    'auth.js',
    'navigation.js',
    'modals.js',
    'image-upload.js',
    'wysiwyg.js',

    # Renderers
    'renderers/stats.js',
    'renderers/masters.js',
    'renderers/services.js',
    'renderers/articles.js',
    'renderers/faq.js',
    'renderers/social.js',

    # Forms
    'forms/master-form.js',
    'forms/service-form.js',
    'forms/article-form.js',
    'forms/faq-form.js',

    # Main entry point (последний, зависит от всех)
    'index.js',
]

# Пути
BASE_DIR = Path(__file__).parent.parent  # Корень проекта (на уровень выше scripts/)
SRC_DIR = BASE_DIR / 'src'
SECTIONS_DIR = SRC_DIR / 'sections'
OUTPUT_FILE = BASE_DIR / 'index.html'  # В корне для совместимости с сервером
ADMIN_MODULES_DIR = SRC_DIR / 'js' / 'admin'
ADMIN_BUNDLE_FILE = SRC_DIR / 'js' / 'admin.bundle.js'


def build():
    """Собирает index.html из секций."""
    parts = []

    for section in SECTIONS:
        section_path = SECTIONS_DIR / section
        if not section_path.exists():
            print(f'⚠️  Секция не найдена: {section}')
            continue

        content = section_path.read_text(encoding='utf-8')
        parts.append(content)

    # Собираем финальный HTML
    html = '\n'.join(parts)

    # Записываем результат
    OUTPUT_FILE.write_text(html, encoding='utf-8')
    print(f'✅ Собран index.html ({len(html):,} байт)')

    return html


def build_admin():
    """Собирает admin.bundle.js из модулей."""
    parts = []

    # Заголовок бандла
    header = '''/**
 * Say's Barbers Admin Panel Bundle
 * Auto-generated by build.py - DO NOT EDIT DIRECTLY
 * Edit individual modules in src/js/admin/ instead
 */

'''
    parts.append(header)

    for module in ADMIN_MODULES:
        module_path = ADMIN_MODULES_DIR / module
        if not module_path.exists():
            print(f'⚠️  Модуль не найден: {module}')
            continue

        content = module_path.read_text(encoding='utf-8')
        # Добавляем комментарий с именем файла для отладки
        parts.append(f'\n// ============= {module} =============\n')
        parts.append(content)

    # Собираем бандл
    bundle = '\n'.join(parts)

    # Записываем результат
    ADMIN_BUNDLE_FILE.write_text(bundle, encoding='utf-8')
    print(f'✅ Собран admin.bundle.js ({len(bundle):,} байт, {len(ADMIN_MODULES)} модулей)')

    return bundle


def get_admin_modules_mtime():
    """Возвращает максимальное время модификации admin модулей."""
    max_mtime = 0
    for module in ADMIN_MODULES:
        module_path = ADMIN_MODULES_DIR / module
        if module_path.exists():
            mtime = module_path.stat().st_mtime
            if mtime > max_mtime:
                max_mtime = mtime
    return max_mtime


def get_sections_mtime():
    """Возвращает максимальное время модификации секций."""
    max_mtime = 0
    for section in SECTIONS:
        section_path = SECTIONS_DIR / section
        if section_path.exists():
            mtime = section_path.stat().st_mtime
            if mtime > max_mtime:
                max_mtime = mtime
    return max_mtime


def watch():
    """Следит за изменениями в секциях и admin модулях, пересобирает при изменении."""
    print('👀 Режим наблюдения. Нажмите Ctrl+C для выхода.')

    last_sections_mtime = 0
    last_admin_mtime = 0

    try:
        while True:
            # Проверка секций
            current_sections_mtime = get_sections_mtime()
            if current_sections_mtime > last_sections_mtime:
                if last_sections_mtime > 0:
                    print('🔄 Обнаружены изменения в секциях, пересборка...')
                build()
                last_sections_mtime = current_sections_mtime

            # Проверка admin модулей
            current_admin_mtime = get_admin_modules_mtime()
            if current_admin_mtime > last_admin_mtime:
                if last_admin_mtime > 0:
                    print('🔄 Обнаружены изменения в admin модулях, пересборка...')
                build_admin()
                last_admin_mtime = current_admin_mtime

            time.sleep(1)
    except KeyboardInterrupt:
        print('\n👋 Наблюдение остановлено.')


def build_all():
    """Собирает и index.html и admin.bundle.js."""
    build()
    build_admin()


if __name__ == '__main__':
    if '--watch' in sys.argv or '-w' in sys.argv:
        build_all()
        watch()
    elif '--admin-only' in sys.argv:
        build_admin()
    elif '--html-only' in sys.argv:
        build()
    else:
        build_all()
